const types = {
  LOGIN_HAS_ERRORED : 'LOGIN_HAS_ERRORED',
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  RESTORE_SUCCESS : 'RESTORE_SUCCESS',
  REGISTRATION_SUCCESS : 'REGISTRATION_SUCCESS',

  REG_STEP_1_SUCCESS : 'REG_STEP_1_SUCCESS',
  REG_STEP_2_1_SUCCESS : 'REG_STEP_2_1_SUCCESS',
  REG_STEP_2_2_SUCCESS : 'REG_STEP_2_2_SUCCESS',
  REG_STEP_3_SUCCESS : 'REG_STEP_3_SUCCESS',
  REG_STEP_4_SUCCESS : 'REG_STEP_4_SUCCESS',
  REG_STEP_5_SUCCESS : 'REG_STEP_5_SUCCESS',


  OTP_SUCCESS : 'OTP_SUCCESS',
  TERMS_SUCCESS : 'TERMS_SUCCESS',
  SIGN_OUT : 'SIGN_OUT',
  SIGN_IN : 'SIGN_IN',
  SIGN_UP : 'SIGN_UP',
  SELECT_SUBREDDIT : 'SELECT_SUBREDDIT',
  INVALIDATE_KEY : 'INVALIDATE_KEY',
  REQUEST_KEY : 'REQUEST_KEY',
  RECEIVE_KEY : 'RECEIVE_KEY',
};
export default types;
