const types = {
  USER_INVALIDATE : 'USER_INVALIDATE',
  USER_RECEIVE : 'USER_RECEIVE',
  USER_UPDATE_TOKEN : 'USER_UPDATE_TOKEN',
  USER_GETTING_TOKEN : 'USER_GETTING_TOKEN',
};
export default types;
